bag_to_csv_node:
  ros__parameters:
    # packages_to_register: # All the messages are registered
      # - custom_msgs
    extractors_to_import:
      - forces_extractor
      - relative_position_extractor

    # custom_msgs: msg # The messages are registered in the msg folder

    forces_extractor:
      package_name: "collab_transport_analysis"
      module_name: "forces_extractor"
      class_name: "ForcesExtractor"
      topics: ["force_torque_sensor_broadcaster/wrench"]

    relative_position_extractor:
      package_name: "collab_transport_analysis"
      module_name: "relative_position_extractor"
      class_name: "RelativePositionExtractor"  
      topics: ["bases_relative_position", "tools_relative_position"]
